### ISSUE TITLE
No module named

### ISSUE THREAD

**Issue by li-marigold** [Rulesobeyer/Optimized-Tris-to-Quads-Converter#1]
It shows me: No module named 'Optimized-Tris-to-Quads-Converter-1' during activation of installed plugin( What it can be?(

**Comment by Rulesobeyer** [comment]
Sorry, mistake on my end. I've pushed a new release that should fix it.

**Comment by li-marigold** [comment]
> Sorry, mistake on my end. I've pushed a new release that should fix it.

working! Thanks so much!
